### ISSUE TITLE
Find someone to help with JSON RPC work

### ISSUE THREAD

**Issue by alita-moore** [ethereum-cat-herders/PM#188]
The current proposed JSON RPC timeline is as follows:
<img width="815" alt="Screen Shot 2021-06-04 at 5 25 20 PM" src="https://user-images.githubusercontent.com/26529820/120868522-d9b1c700-c559-11eb-8452-e9e9e1633dd7.png">

@tkstanczak has relayed to me that the `nethermind` would like to reduce the proposed timeline. To do this they have asked me to find a full time person to help me and that I would project manage part time (plus do work as well as possible of course). It may be difficult to find a full-time contracted individual, so I have designed an easily scalable (among however many people to meet the expected timeframe) which is described here:
https://github.com/ethereum-cat-herders/PM/issues/185

To be clear there are three steps to this ticket
- [ ] build the job description: https://github.com/ethereum-cat-herders/PM/issues/185
- [ ] advertise the job description: https://github.com/ethereum-cat-herders/PM/issues/186
- [ ] onboard / update this ticket with results: https://github.com/ethereum-cat-herders/PM/issues/187

**Comment by DockBoss** [comment]
I would love to help if you need people.

**Comment by alita-moore** [comment]
@DockBoss awesome! I don't have the specification yet on compensation + time commitment, but how many hours (max) do you think you could work?

**Comment by DockBoss** [comment]
I could work 40+ hours a week if needed.

**Comment by alita-moore** [comment]
@DockBoss that's interesting. Reach out to me on discord at Alita#5791 and we can talk more about the exact requirements of this. It's a very good learning opportunity.

**Comment by poojaranjan** [comment]
@alita-moore  Is there a decision or need for more application? If so happy to include it in the upcoming newsletter to invite more participation. Let me know!

**Comment by alita-moore** [comment]
@poojaranjan things are going well with @DockBoss i still want to wait until next week to make a final decision, but so far so good. I.e. Not at the moment

**Comment by poojaranjan** [comment]
Cool! I am not adding in the upcoming newsletter. Will revisit on June 18th. Thank @alita-moore !
